In [5]:
import pandas as pd
import numpy as np

In [6]:
data = {
    "N_candidat": ["0001", "0002", "0003", "0004", "0005"],
    "S1":[15, 13, 16, 17, 13],
    "S2": [11, 9, 8, 12, 10],
    "S3":[14, 12, 11, 15, 13],
    "S4": [16, 15, 15, 18, 15],
    "S5": [11, 11, 11, 11, 11],

    "Logique": [1, 1, 1, 0, 0],
    "BDD": [1, 1, 1, 0, 0],
    "PS": [1, 1, 1, 1, 0],
    "Moyenne": [2, 0, 1, 2, 0],
    "Eligible": [True, True, True, False, False],
    "Decision": ['A','R','L','R','R']
}

df= pd.DataFrame(data)
df

  N_candidat  S1  S2  S3  S4  S5  Logique  BDD  PS  Moyenne  Eligible Decision
0       0001  15  11  14  16  11        1    1   1        2      True        A
1       0002  13   9  12  15  11        1    1   1        0      True        R
2       0003  16   8  11  15  11        1    1   1        1      True        L
3       0004  17  12  15  18  11        0    0   1        2     False        R
4       0005  13  10  13  15  11        0    0   0        0     False        R

In [10]:
def AC1(N, X, decision, df=df):
    c = df[df.N_candidat == N].copy()
    return len(c) == 1 and c.Decision.iloc[0] == decision and all(str(c.loc[:, [a]].iloc[0, 0]) == str(X[a]) for a in X)

In [11]:
print(" Cas succès 1 : ", AC1("0001", {"Logique":"1"}, 'A'))
print(" Cas succès 2 : ", AC1("0001", {"S1":"15", "BDD":"1", "Moyenne":"2", 'Eligible': True}, 'A'))
print(" Cas succès 3 : ", AC1("0004", {"S2":"12", "BDD":"0"}, 'R'))

print(" Cas échec 1 : ", AC1("0001", {"S1":"15", "BDD":"1", "Moyenne":"2", 'Eligible': False}, 'A'))
print(" Cas échec 2 : ", AC1("xxxx", {"S1":"15", "BDD":"1", "Moyenne":"2", 'Eligible': True}, 'A'))

 Cas succès 1 :  True
 Cas succès 2 :  True
 Cas succès 3 :  True
 Cas échec 1 :  False
 Cas échec 2 :  False